DROP TABLE IF EXISTS CONVERSION_DETAILS;
CREATE TABLE CONVERSION_DETAILS (id INT AUTO_INCREMENT PRIMARY KEY , country_code CHAR(3) NOT NULL, conversion_factor decimal(20,2) NOT NULL, CONSTRAINT UC_CONVERSION_DETAILS UNIQUE(country_code));
INSERT INTO CONVERSION_DETAILS (country_code, conversion_factor) VALUES
('AUS', 50.00),
('CAN', 60.00),
('UK', 95.00),
('USA', 75.00);

